apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-child
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PujanPraz/argocd-demos.git
    targetRevision: main
    path: ui_approach/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
